apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-e2e
  namespace: poc-dev
spec:
  chart:
    spec:
      chart: ./charts/azure-keyvault-e2e
      sourceRef:
        kind: HelmRepository
        name: saipocregistry.azurecr.io
  interval: 1m
  values:
    image:
      repository: saipocregistry.azurecr.io/dmo/azure-keyvault-e2e
      tag: latest
