apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-e2e
  namespace: poc-dev  # Ensure this is correct
spec:
  chart:
    spec:
      chart: charts/azure-keyvault-e2e  # Correct path (NO `./`)
      sourceRef:
        kind: GitRepository  # Since the chart is stored in Git
        name: flux-system  # Your GitRepository name
        namespace: flux-system  # GitRepo namespace
  interval: 1m
  values:
    image:
      repository: saipocregistry.azurecr.io/azure-keyvault-e2e
      tag: latest
