apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: azure-keyvault-e2e-policy-dev
  namespace: flux-system
spec:
  filterTags:
    extract: '$ts'
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
  imageRepositoryRef:
    name: azure-keyvault-e2e-dev
  policy:
    numerical:
      order: asc
